require 'options'
require 'keymaps'
require 'autocmds'

require 'plugins.catppuccin'
require 'plugins.treesitter'
require 'plugins.telescope'
require 'plugins.lsp'
require 'plugins.conform'
require 'plugins.dressing'
